optimizer = "nadam"
lr = 0.001
lr_scheduler = "reduce_on_plateau"
dropout = 0.05
hidden_layers = 2
hidden_size = 128
normalization = "layer"
batch_size = 8
base_model = "michiyasunaga/BioLinkBERT-base"