optimizer = ["adamw", "adam", "nadam"]
lr = [0.0003, 0.003, 0.01, 0.1, 0.001]
lr_scheduler = ["reduce_on_plateau", "exponential"]
dropout = [0, 0.1, 0.2, 0.3]
normalization = ["layer", "batch"]
batch_max_chunks = [64]
batch_size = [2]
base_model = ["michiyasunaga/BioLinkBERT-base"]
relation_label_smoothing = [0, 0.1]
hidden_layers = [64, 64, 32]
common_hidden_block = [true, false]
ramp_epochs = [4, 8, 0]
separate_predicate_layer = [true, false]
model_class = ["NERClassificationModel"]
